version: '3'
services:
  db:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: 123456aA@
    ports:
      - "3307:3306"
    volumes:
      - /opt/mysql/data:/var/lib/mysql
    restart: always
    networks:
      - vsap-networks
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - vsap-networks
networks:
  vsap-networks:
    driver: bridge
volumes:
  vsap-volumes:
